"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class single_joint_command_t(object):
    """
    @brief 单个关节的控制命令
    
    """

    __slots__ = ["pos", "vel"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.pos = 0.0
        """
        目标位置
        LCM Type: float
        """

        self.vel = 0.0
        """
        目标速度  
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(single_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ff", self.pos, self.vel))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != single_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return single_joint_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = single_joint_command_t()
        self.pos, self.vel = struct.unpack(">ff", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if single_joint_command_t in parents: return 0
        tmphash = (0xc63bc8eb2c8de205) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if single_joint_command_t._packed_fingerprint is None:
            single_joint_command_t._packed_fingerprint = struct.pack(">Q", single_joint_command_t._get_hash_recursive([]))
        return single_joint_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", single_joint_command_t._get_packed_fingerprint())[0]

