"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class single_joint_state_t(object):
    """
    @brief 单个关节的状态
    
    """

    __slots__ = ["status_word", "posH", "posL", "vel", "toq", "current", "err_code"]

    __typenames__ = ["int16_t", "float", "float", "float", "float", "float", "int16_t"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.status_word = 0
        """
        当前关节状态
        LCM Type: int16_t
        """

        self.posH = 0.0
        """
        当前关节位置, 高编
        LCM Type: float
        """

        self.posL = 0.0
        """
        当前关节位置，低编
        LCM Type: float
        """

        self.vel = 0.0
        """
        当前速度
        LCM Type: float
        """

        self.toq = 0.0
        """
        当前力矩
        LCM Type: float
        """

        self.current = 0.0
        """
        当前电流
        LCM Type: float
        """

        self.err_code = 0
        """
        错误码
        LCM Type: int16_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(single_joint_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hfffffh", self.status_word, self.posH, self.posL, self.vel, self.toq, self.current, self.err_code))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != single_joint_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return single_joint_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = single_joint_state_t()
        self.status_word, self.posH, self.posL, self.vel, self.toq, self.current, self.err_code = struct.unpack(">hfffffh", buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if single_joint_state_t in parents: return 0
        tmphash = (0x11ee4d4379ef2430) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if single_joint_state_t._packed_fingerprint is None:
            single_joint_state_t._packed_fingerprint = struct.pack(">Q", single_joint_state_t._get_hash_recursive([]))
        return single_joint_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", single_joint_state_t._get_packed_fingerprint())[0]

