"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import manipulation.gripper

class gripper_state_t(object):
    """
    @brief 整个夹爪状态信息 左0右1
    
    """

    __slots__ = ["timestamp", "state"]

    __typenames__ = ["int64_t", "manipulation.gripper.single_gripper_joint_state_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        """
        时间戳（纳秒）
        LCM Type: int64_t
        """

        self.state = manipulation.gripper.single_gripper_joint_state_t()
        """
        所有手部关节状态          
        LCM Type: manipulation.gripper.single_gripper_joint_state_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(gripper_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        assert self.state._get_packed_fingerprint() == manipulation.gripper.single_gripper_joint_state_t._get_packed_fingerprint()
        self.state._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gripper_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gripper_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = gripper_state_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.state = manipulation.gripper.single_gripper_joint_state_t._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if gripper_state_t in parents: return 0
        newparents = parents + [gripper_state_t]
        tmphash = (0xb482900348c5237b+ manipulation.gripper.single_gripper_joint_state_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if gripper_state_t._packed_fingerprint is None:
            gripper_state_t._packed_fingerprint = struct.pack(">Q", gripper_state_t._get_hash_recursive([]))
        return gripper_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", gripper_state_t._get_packed_fingerprint())[0]

