"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class single_gripper_joint_command_t(object):
    """
    @brief 单个夹爪关节的控制命令
    
    """

    __slots__ = ["pos"]

    __typenames__ = ["float"]

    __dimensions__ = [[1]]

    def __init__(self):
        self.pos = [ 0.0 for dim0 in range(1) ]
        """
        期望位置
        LCM Type: float[1]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(single_gripper_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>1f', *self.pos[:1]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != single_gripper_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return single_gripper_joint_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = single_gripper_joint_command_t()
        self.pos = struct.unpack('>1f', buf.read(4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if single_gripper_joint_command_t in parents: return 0
        tmphash = (0xe6a097ab2019abcf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if single_gripper_joint_command_t._packed_fingerprint is None:
            single_gripper_joint_command_t._packed_fingerprint = struct.pack(">Q", single_gripper_joint_command_t._get_hash_recursive([]))
        return single_gripper_joint_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", single_gripper_joint_command_t._get_packed_fingerprint())[0]

