"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class single_gripper_joint_state_t(object):
    """
    @brief 单个夹爪关节的状态
    
    """

    __slots__ = ["status_word", "pos", "toq", "cur", "error_code"]

    __typenames__ = ["int16_t", "float", "float", "float", "int16_t"]

    __dimensions__ = [None, [1], [1], [1], None]

    def __init__(self):
        self.status_word = 0
        """
        状态字
        LCM Type: int16_t
        """

        self.pos = [ 0.0 for dim0 in range(1) ]
        """
        实际位置
        LCM Type: float[1]
        """

        self.toq = [ 0.0 for dim0 in range(1) ]
        """
        实际力矩
        LCM Type: float[1]
        """

        self.cur = [ 0.0 for dim0 in range(1) ]
        """
        实际电流
        LCM Type: float[1]
        """

        self.error_code = 0
        """
        错误码
        LCM Type: int16_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(single_gripper_joint_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.status_word))
        buf.write(struct.pack('>1f', *self.pos[:1]))
        buf.write(struct.pack('>1f', *self.toq[:1]))
        buf.write(struct.pack('>1f', *self.cur[:1]))
        buf.write(struct.pack(">h", self.error_code))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != single_gripper_joint_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return single_gripper_joint_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = single_gripper_joint_state_t()
        self.status_word = struct.unpack(">h", buf.read(2))[0]
        self.pos = struct.unpack('>1f', buf.read(4))
        self.toq = struct.unpack('>1f', buf.read(4))
        self.cur = struct.unpack('>1f', buf.read(4))
        self.error_code = struct.unpack(">h", buf.read(2))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if single_gripper_joint_state_t in parents: return 0
        tmphash = (0x8aaa9aba8875c486) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if single_gripper_joint_state_t._packed_fingerprint is None:
            single_gripper_joint_state_t._packed_fingerprint = struct.pack(">Q", single_gripper_joint_state_t._get_hash_recursive([]))
        return single_gripper_joint_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", single_gripper_joint_state_t._get_packed_fingerprint())[0]

