"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class robot_info_t(object):
    """
    @brief 通用机器人信息
    
    """

    __slots__ = ["timestamp_ns", "vendor", "robot_id", "robot_type", "controller_version", "joint_num", "power_state", "operate_mode", "operation_state", "connected"]

    __typenames__ = ["int64_t", "string", "string", "string", "string", "int32_t", "int16_t", "int16_t", "int16_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.timestamp_ns = 0
        """
        时间戳（纳秒）
        LCM Type: int64_t
        """

        self.vendor = ""
        """
        厂家名称 (e.g. "Rokae", "UR", "ABB")
        LCM Type: string
        """

        self.robot_id = ""
        """
        机器人 ID
        LCM Type: string
        """

        self.robot_type = ""
        """
        机型名称
        LCM Type: string
        """

        self.controller_version = ""
        """
        控制器版本
        LCM Type: string
        """

        self.joint_num = 0
        """
        关节数
        LCM Type: int32_t
        """

        self.power_state = 0
        """
        上电状态: 0=off, 1=on, 2=estop, 3=gstop
        LCM Type: int16_t
        """

        self.operate_mode = 0
        """
        操作模式: 0=manual, 1=automatic
        LCM Type: int16_t
        """

        self.operation_state = 0
        """
        运行状态: 0=idle, 2=rtControlling, 9=moving
        LCM Type: int16_t
        """

        self.connected = 0
        """
        是否已连接
        LCM Type: int8_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(robot_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp_ns))
        __vendor_encoded = self.vendor.encode('utf-8')
        buf.write(struct.pack('>I', len(__vendor_encoded)+1))
        buf.write(__vendor_encoded)
        buf.write(b"\0")
        __robot_id_encoded = self.robot_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__robot_id_encoded)+1))
        buf.write(__robot_id_encoded)
        buf.write(b"\0")
        __robot_type_encoded = self.robot_type.encode('utf-8')
        buf.write(struct.pack('>I', len(__robot_type_encoded)+1))
        buf.write(__robot_type_encoded)
        buf.write(b"\0")
        __controller_version_encoded = self.controller_version.encode('utf-8')
        buf.write(struct.pack('>I', len(__controller_version_encoded)+1))
        buf.write(__controller_version_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ihhhb", self.joint_num, self.power_state, self.operate_mode, self.operation_state, self.connected))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_info_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_info_t()
        self.timestamp_ns = struct.unpack(">q", buf.read(8))[0]
        __vendor_len = struct.unpack('>I', buf.read(4))[0]
        self.vendor = buf.read(__vendor_len)[:-1].decode('utf-8', 'replace')
        __robot_id_len = struct.unpack('>I', buf.read(4))[0]
        self.robot_id = buf.read(__robot_id_len)[:-1].decode('utf-8', 'replace')
        __robot_type_len = struct.unpack('>I', buf.read(4))[0]
        self.robot_type = buf.read(__robot_type_len)[:-1].decode('utf-8', 'replace')
        __controller_version_len = struct.unpack('>I', buf.read(4))[0]
        self.controller_version = buf.read(__controller_version_len)[:-1].decode('utf-8', 'replace')
        self.joint_num, self.power_state, self.operate_mode, self.operation_state, self.connected = struct.unpack(">ihhhb", buf.read(11))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_info_t in parents: return 0
        tmphash = (0x4d99831eeda04136) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_info_t._packed_fingerprint is None:
            robot_info_t._packed_fingerprint = struct.pack(">Q", robot_info_t._get_hash_recursive([]))
        return robot_info_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_info_t._get_packed_fingerprint())[0]

