"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class left_tracker_pos(object):

    __slots__ = ["x", "y", "z"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.x = 0.0
        """ LCM Type: float """
        self.y = 0.0
        """
        左手位置 x,y,z
        LCM Type: float
        """

        self.z = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(left_tracker_pos._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.x, self.y, self.z))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != left_tracker_pos._get_packed_fingerprint():
            raise ValueError("Decode error")
        return left_tracker_pos._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = left_tracker_pos()
        self.x, self.y, self.z = struct.unpack(">fff", buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if left_tracker_pos in parents: return 0
        tmphash = (0x2a14f112c253ac0c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if left_tracker_pos._packed_fingerprint is None:
            left_tracker_pos._packed_fingerprint = struct.pack(">Q", left_tracker_pos._get_hash_recursive([]))
        return left_tracker_pos._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", left_tracker_pos._get_packed_fingerprint())[0]

