"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class teleop_recording_data_t(object):

    __slots__ = ["left_position"]

    __typenames__ = ["float"]

    __dimensions__ = [[3]]

    def __init__(self):
        self.left_position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(teleop_recording_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.left_position[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != teleop_recording_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return teleop_recording_data_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = teleop_recording_data_t()
        self.left_position = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if teleop_recording_data_t in parents: return 0
        tmphash = (0x77eadfe0bf4568e8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if teleop_recording_data_t._packed_fingerprint is None:
            teleop_recording_data_t._packed_fingerprint = struct.pack(">Q", teleop_recording_data_t._get_hash_recursive([]))
        return teleop_recording_data_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", teleop_recording_data_t._get_packed_fingerprint())[0]

