dof:
  value: 30

urdf_path_l:
  value: "models/URDF_Gen1/l_arm_v1.urdf"

urdf_path_r:
  value: "models/URDF_Gen1/r_arm_v1.urdf"

ReadyPos_l:
  value: [0.0, 0.5, 1.5707963, -1.5, -1.5707963]

ReadyPos_r:
  value: [0.0, -0.5, -1.5707963, 1.5, 1.5707963]

init_qpos:
  value: [  0, 0, 1.5707963, -1.5707963, -1.5707963, 0, 0, 
            0, 0, -1.5707963, 1.5707963, 1.5707963, 0, 0, 
            3.0, 3.0, 3.0, 3.0, 0.92, 2.86, 
            3.0, 3.0, 3.0, 3.0, 0.92, 2.86, 
            0, 0, 0, 0]

ready_pos:
  value: [  0.0, 0.5, 1.5707963, -1.5, -1.5707963, 0.52, 0.0, 
            0.0, -0.5, -1.5707963, 1.5, 1.5707963, -0.52, 0.0, 
            3.0, 3.0, 3.0, 3.0, 0.92, 2.86, 
            3.0, 3.0, 3.0, 3.0, 0.92, 2.86, 
            0.01, 0.0, -0.0, 0.0]

ee_frame_name_l:
  value: "link_tcp_l"

ee_frame_name_r:
  value: "link_tcp_r"

move2first_steps:
  - pre_from_prev: false
    updates:
      "1": 0.3
      "8": -0.3
      "5": 0.52
      "12": -0.52
  - pre_from_prev: true
    updates:
      "0": 0.2
      "7": 0.2
      "2": 1.5707963
      "4": -1.5707963
      "9": -1.5707963
      "11": 1.5707963
      "5": 0
      "6": 0
      "12": 0
      "26": 0.0
      "27": 0.0
      "28": 0.0
      "29": 0.0
  - pre_from_prev: true
    updates:
      "0": 1
      "7": 1
      "1": 0.5
      "8": -0.5
      "3": -1.7
      "10": 1.7
      "12": 0
  - pre_from_prev: true
    updates:
      "0": 0
      "7": 0
      "3": -1.5
      "10": 1.5
      # "12": 0
      "5": 0.52
      "12": -0.52

move2stand_steps:
  - updates:
      "0": 1
      "7": 1
      "1": 1
      "8": -1
  - pre_from_prev: false
    updates:
      "0": 1
      "7": 1
      "1": 1
      "8": -1
      "3": -1.7
      "10": 1.7
  - pre_from_prev: true
    updates:
      "0": 0
      "7": 0
      "3": 0
      "10": 0
  - pre_from_prev: true
    updates:
      "0": 0.03
      "7": 0.03
      "2": 0
      "4": 0
      "9": 0
      "11": 0
  - full: !!seq
      - 0.08; 0.2; 1.0; -0.3; -1.0; 0.0; 0.1; 0.08; -0.2; -1.0; 0.3; 1.0; 0.0; 0.1; 3.08; 3.08; 3.08; 3.08; 0.93; 2.86; 3.08; 3.08; 3.08; 3.08; 0.93; 2.86; 0.0; 0.0; 0.0; 0.0
