"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import manipulation.joint

class joint_state_t(object):
    """
    @brief 整个头部关节状态数据
    
    """

    __slots__ = ["timestamp", "joints"]

    __typenames__ = ["int64_t", "manipulation.joint.single_joint_state_t"]

    __dimensions__ = [None, [2]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.joints = [ manipulation.joint.single_joint_state_t() for dim0 in range(2) ]
        """ LCM Type: manipulation.joint.single_joint_state_t[2] """

    def encode(self):
        buf = BytesIO()
        buf.write(joint_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        for i0 in range(2):
            assert self.joints[i0]._get_packed_fingerprint() == manipulation.joint.single_joint_state_t._get_packed_fingerprint()
            self.joints[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = joint_state_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.joints = []
        for i0 in range(2):
            self.joints.append(manipulation.joint.single_joint_state_t._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if joint_state_t in parents: return 0
        newparents = parents + [joint_state_t]
        tmphash = (0x50bf32ee95033221+ manipulation.joint.single_joint_state_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if joint_state_t._packed_fingerprint is None:
            joint_state_t._packed_fingerprint = struct.pack(">Q", joint_state_t._get_hash_recursive([]))
        return joint_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", joint_state_t._get_packed_fingerprint())[0]

