# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import xrTracking_pb2 as xrTracking__pb2
# from mocap_system.stream.pico.grpc_msg import xrTracking_pb2 as xrTracking__pb2
GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xrTracking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamControllerUpdates = channel.unary_stream(
                '/xrTracking.TrackingService/StreamControllerUpdates',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=xrTracking__pb2.ControllerUpdate.FromString,
                _registered_method=True)
        self.StreamHandUpdates = channel.unary_stream(
                '/xrTracking.TrackingService/StreamHandUpdates',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=xrTracking__pb2.HandUpdate.FromString,
                _registered_method=True)
        self.StreamMotionTrackerKeyAction = channel.unary_stream(
                '/xrTracking.TrackingService/StreamMotionTrackerKeyAction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=xrTracking__pb2.MotionTrackerKeyAction.FromString,
                _registered_method=True)
        self.StreamButtonInfo = channel.stream_stream(
                '/xrTracking.TrackingService/StreamButtonInfo',
                request_serializer=xrTracking__pb2.ButtonInfo.SerializeToString,
                response_deserializer=xrTracking__pb2.ButtonInfoResponse.FromString,
                _registered_method=True)


class TrackingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamControllerUpdates(self, request, context):
        """监听控制器追踪
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHandUpdates(self, request, context):
        """监听手部追踪
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMotionTrackerKeyAction(self, request, context):
        """监听追踪器按键
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamButtonInfo(self, request_iterator, context):
        """同步按钮触发的状态
        需要等待客户端收到ButtonInfoResponse之后再发送ButtonInfo，因为涉及到PICO的页面逻辑和国际化
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamControllerUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamControllerUpdates,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=xrTracking__pb2.ControllerUpdate.SerializeToString,
            ),
            'StreamHandUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHandUpdates,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=xrTracking__pb2.HandUpdate.SerializeToString,
            ),
            'StreamMotionTrackerKeyAction': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMotionTrackerKeyAction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=xrTracking__pb2.MotionTrackerKeyAction.SerializeToString,
            ),
            'StreamButtonInfo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamButtonInfo,
                    request_deserializer=xrTracking__pb2.ButtonInfo.FromString,
                    response_serializer=xrTracking__pb2.ButtonInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrTracking.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrTracking.TrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamControllerUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrTracking.TrackingService/StreamControllerUpdates',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            xrTracking__pb2.ControllerUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamHandUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrTracking.TrackingService/StreamHandUpdates',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            xrTracking__pb2.HandUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMotionTrackerKeyAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xrTracking.TrackingService/StreamMotionTrackerKeyAction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            xrTracking__pb2.MotionTrackerKeyAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamButtonInfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/xrTracking.TrackingService/StreamButtonInfo',
            xrTracking__pb2.ButtonInfo.SerializeToString,
            xrTracking__pb2.ButtonInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
